version: '2'
services:
  server:
    build: .
    image: family_tree_server
    container_name: family_tree_server
    stdin_open: true
    tty: true
    volumes:
      - .:/src
    ports:
      - "8080"
    networks:
      - main_network
    command: npm run dev # We only use compose locally

  mongo:
    container_name: family_tree_server_db
    image: mongo:3.4
    ports:
      - "27019:27017"

networks:
  main_network:
    driver: bridge
